#include <llvm-c/Analysis.h>
#include <llvm-c/Core.h>
#include <llvm-c/Error.h>
#include <llvm-c/ExecutionEngine.h>
#include <llvm-c/Support.h>
#include <llvm-c/Target.h>
#include <llvm-c/TargetMachine.h>
#include <llvm-c/Transforms/PassManagerBuilder.h>

// llvm0 and llvm-sys compatible wrapper functions

LLVMBool LLVM_InitializeNativeTarget() {
  return LLVMInitializeNativeTarget();
}

LLVMBool LLVM_InitializeNativeAsmPrinter() {
  return LLVMInitializeNativeAsmPrinter();
}

LLVMBool LLVM_InitializeNativeAsmParser() {
  return LLVMInitializeNativeAsmParser();
}

LLVMBool LLVM_InitializeNativeDisassembler() {
  return LLVMInitializeNativeDisassembler();
}

typedef struct {
  const char *name;
  uint64_t addr;
} llvm_symbol;

typedef struct {
  llvm_symbol *ptr;
  uint64_t len;
} llvm_symbol_array;

llvm_symbol_array llvm_symbols();

#define LLVM_SYMBOL(name) {#name, (uint64_t) name}

static llvm_symbol symbols[] = {
  LLVM_SYMBOL(llvm_symbols),
  LLVM_SYMBOL(LLVMABIAlignmentOfType),
  LLVM_SYMBOL(LLVMABISizeOfType),
  LLVM_SYMBOL(LLVMAddFunction),
  LLVM_SYMBOL(LLVMAddGlobal),
  LLVM_SYMBOL(LLVMAddGlobalInAddressSpace),
  LLVM_SYMBOL(LLVMAddIncoming),
  LLVM_SYMBOL(LLVMAddModule),
  LLVM_SYMBOL(LLVMAddSymbol),
  LLVM_SYMBOL(LLVMAlignOf),
  LLVM_SYMBOL(LLVMAppendBasicBlockInContext),
  LLVM_SYMBOL(LLVMArrayType),
  LLVM_SYMBOL(LLVMBuildAShr),
  LLVM_SYMBOL(LLVMBuildAdd),
  LLVM_SYMBOL(LLVMBuildAddrSpaceCast),
  LLVM_SYMBOL(LLVMBuildAlloca),
  LLVM_SYMBOL(LLVMBuildAnd),
  LLVM_SYMBOL(LLVMBuildArrayAlloca),
  LLVM_SYMBOL(LLVMBuildBitCast),
  LLVM_SYMBOL(LLVMBuildBr),
  LLVM_SYMBOL(LLVMBuildCall),
  LLVM_SYMBOL(LLVMBuildCondBr),
  LLVM_SYMBOL(LLVMBuildExtractValue),
  LLVM_SYMBOL(LLVMBuildFAdd),
  LLVM_SYMBOL(LLVMBuildFCmp),
  LLVM_SYMBOL(LLVMBuildFDiv),
  LLVM_SYMBOL(LLVMBuildFMul),
  LLVM_SYMBOL(LLVMBuildFNeg),
  LLVM_SYMBOL(LLVMBuildFPExt),
  LLVM_SYMBOL(LLVMBuildFPToSI),
  LLVM_SYMBOL(LLVMBuildFPToUI),
  LLVM_SYMBOL(LLVMBuildFPTrunc),
  LLVM_SYMBOL(LLVMBuildFRem),
  LLVM_SYMBOL(LLVMBuildFSub),
  LLVM_SYMBOL(LLVMBuildGEP),
  LLVM_SYMBOL(LLVMBuildICmp),
  LLVM_SYMBOL(LLVMBuildInsertValue),
  LLVM_SYMBOL(LLVMBuildIntToPtr),
  LLVM_SYMBOL(LLVMBuildLShr),
  LLVM_SYMBOL(LLVMBuildLoad),
  LLVM_SYMBOL(LLVMBuildMul),
  LLVM_SYMBOL(LLVMBuildNSWAdd),
  LLVM_SYMBOL(LLVMBuildNSWMul),
  LLVM_SYMBOL(LLVMBuildNSWNeg),
  LLVM_SYMBOL(LLVMBuildNSWSub),
  LLVM_SYMBOL(LLVMBuildNeg),
  LLVM_SYMBOL(LLVMBuildNot),
  LLVM_SYMBOL(LLVMBuildOr),
  LLVM_SYMBOL(LLVMBuildPhi),
  LLVM_SYMBOL(LLVMBuildPtrToInt),
  LLVM_SYMBOL(LLVMBuildRet),
  LLVM_SYMBOL(LLVMBuildRetVoid),
  LLVM_SYMBOL(LLVMBuildSDiv),
  LLVM_SYMBOL(LLVMBuildSExt),
  LLVM_SYMBOL(LLVMBuildSIToFP),
  LLVM_SYMBOL(LLVMBuildSRem),
  LLVM_SYMBOL(LLVMBuildSelect),
  LLVM_SYMBOL(LLVMBuildShl),
  LLVM_SYMBOL(LLVMBuildStore),
  LLVM_SYMBOL(LLVMBuildStructGEP),
  LLVM_SYMBOL(LLVMBuildSub),
  LLVM_SYMBOL(LLVMBuildTrunc),
  LLVM_SYMBOL(LLVMBuildUDiv),
  LLVM_SYMBOL(LLVMBuildUIToFP),
  LLVM_SYMBOL(LLVMBuildURem),
  LLVM_SYMBOL(LLVMBuildUnreachable),
  LLVM_SYMBOL(LLVMBuildXor),
  LLVM_SYMBOL(LLVMBuildZExt),
  LLVM_SYMBOL(LLVMByteOrder),
  LLVM_SYMBOL(LLVMCloneModule),
  LLVM_SYMBOL(LLVMConstAllOnes),
  LLVM_SYMBOL(LLVMConstArray),
  LLVM_SYMBOL(LLVMConstBitCast),
  LLVM_SYMBOL(LLVMConstInt),
  LLVM_SYMBOL(LLVMConstIntGetSExtValue),
  LLVM_SYMBOL(LLVMConstIntGetZExtValue),
  LLVM_SYMBOL(LLVMConstIntToPtr),
  LLVM_SYMBOL(LLVMConstNamedStruct),
  LLVM_SYMBOL(LLVMConstNull),
  LLVM_SYMBOL(LLVMConstPtrToInt),
  LLVM_SYMBOL(LLVMConstReal),
  LLVM_SYMBOL(LLVMConstRealGetDouble),
  LLVM_SYMBOL(LLVMConstStringInContext),
  LLVM_SYMBOL(LLVMConstStructInContext),
  LLVM_SYMBOL(LLVMConstTruncOrBitCast),
  LLVM_SYMBOL(LLVMConstVector),
  LLVM_SYMBOL(LLVMConsumeError),
  LLVM_SYMBOL(LLVMContextCreate),
  LLVM_SYMBOL(LLVMContextDispose),
  LLVM_SYMBOL(LLVMCopyStringRepOfTargetData),
  LLVM_SYMBOL(LLVMCountBasicBlocks),
  LLVM_SYMBOL(LLVMCountParamTypes),
  LLVM_SYMBOL(LLVMCountParams),
  LLVM_SYMBOL(LLVMCountStructElementTypes),
  LLVM_SYMBOL(LLVMCreateBuilderInContext),
  LLVM_SYMBOL(LLVMCreateFunctionPassManagerForModule),
  LLVM_SYMBOL(LLVMCreateInterpreterForModule),
  LLVM_SYMBOL(LLVMCreateMCJITCompilerForModule),
  LLVM_SYMBOL(LLVMCreateMessage),
  LLVM_SYMBOL(LLVMCreatePassManager),
  LLVM_SYMBOL(LLVMCreateTargetData),
  LLVM_SYMBOL(LLVMCreateTargetDataLayout),
  LLVM_SYMBOL(LLVMCreateTargetMachine),
  LLVM_SYMBOL(LLVMDeleteBasicBlock),
  LLVM_SYMBOL(LLVMDeleteFunction),
  LLVM_SYMBOL(LLVMDeleteGlobal),
  LLVM_SYMBOL(LLVMDisposeBuilder),
  LLVM_SYMBOL(LLVMDisposeErrorMessage),
  LLVM_SYMBOL(LLVMDisposeExecutionEngine),
  LLVM_SYMBOL(LLVMDisposeMessage),
  LLVM_SYMBOL(LLVMDisposeModule),
  LLVM_SYMBOL(LLVMDisposePassManager),
  LLVM_SYMBOL(LLVMDisposeTargetData),
  LLVM_SYMBOL(LLVMDisposeTargetMachine),
  LLVM_SYMBOL(LLVMDoubleTypeInContext),
  LLVM_SYMBOL(LLVMElementAtOffset),
  LLVM_SYMBOL(LLVMFP128TypeInContext),
  LLVM_SYMBOL(LLVMFinalizeFunctionPassManager),
  LLVM_SYMBOL(LLVMFindFunction),
  LLVM_SYMBOL(LLVMFloatTypeInContext),
  LLVM_SYMBOL(LLVMFunctionType),
  LLVM_SYMBOL(LLVMGetArrayLength),
  LLVM_SYMBOL(LLVMGetAsString),
  LLVM_SYMBOL(LLVMGetBasicBlockName),
  LLVM_SYMBOL(LLVMGetBasicBlockParent),
  LLVM_SYMBOL(LLVMGetBasicBlocks),
  LLVM_SYMBOL(LLVMGetDefaultTargetTriple),
  LLVM_SYMBOL(LLVMGetElementType),
  LLVM_SYMBOL(LLVMGetEntryBasicBlock),
  LLVM_SYMBOL(LLVMGetErrorMessage),
  LLVM_SYMBOL(LLVMGetExecutionEngineTargetData),
  LLVM_SYMBOL(LLVMGetExecutionEngineTargetMachine),
  LLVM_SYMBOL(LLVMGetFirstFunction),
  LLVM_SYMBOL(LLVMGetFirstGlobal),
  LLVM_SYMBOL(LLVMGetFirstInstruction),
  LLVM_SYMBOL(LLVMGetFirstTarget),
  LLVM_SYMBOL(LLVMGetFunctionAddress),
  LLVM_SYMBOL(LLVMGetInitializer),
  LLVM_SYMBOL(LLVMGetInsertBlock),
  LLVM_SYMBOL(LLVMGetIntTypeWidth),
  LLVM_SYMBOL(LLVMGetLinkage),
  LLVM_SYMBOL(LLVMGetModuleContext),
  LLVM_SYMBOL(LLVMGetModuleDataLayout),
  LLVM_SYMBOL(LLVMGetNamedFunction),
  LLVM_SYMBOL(LLVMGetNamedGlobal),
  LLVM_SYMBOL(LLVMGetNextFunction),
  LLVM_SYMBOL(LLVMGetNextGlobal),
  LLVM_SYMBOL(LLVMGetNextTarget),
  LLVM_SYMBOL(LLVMGetParamTypes),
  LLVM_SYMBOL(LLVMGetParams),
  LLVM_SYMBOL(LLVMGetPointerAddressSpace),
  LLVM_SYMBOL(LLVMGetReturnType),
  LLVM_SYMBOL(LLVMGetStructElementTypes),
  LLVM_SYMBOL(LLVMGetStructName),
  LLVM_SYMBOL(LLVMGetTarget),
  LLVM_SYMBOL(LLVMGetTargetDescription),
  LLVM_SYMBOL(LLVMGetTargetFromName),
  LLVM_SYMBOL(LLVMGetTargetFromTriple),
  LLVM_SYMBOL(LLVMGetTargetMachineCPU),
  LLVM_SYMBOL(LLVMGetTargetMachineFeatureString),
  LLVM_SYMBOL(LLVMGetTargetMachineTarget),
  LLVM_SYMBOL(LLVMGetTargetMachineTriple),
  LLVM_SYMBOL(LLVMGetTargetName),
  LLVM_SYMBOL(LLVMGetTypeContext),
  LLVM_SYMBOL(LLVMGetTypeKind),
  LLVM_SYMBOL(LLVMGetUndef),
  LLVM_SYMBOL(LLVMGetValueName2),
  LLVM_SYMBOL(LLVMGetVectorSize),
  LLVM_SYMBOL(LLVMGetVisibility),
  LLVM_SYMBOL(LLVMHalfTypeInContext),
  LLVM_SYMBOL(LLVMInitializeFunctionPassManager),
  LLVM_SYMBOL(LLVMInitializeMCJITCompilerOptions),
  LLVM_SYMBOL(LLVMIntTypeInContext),
  LLVM_SYMBOL(LLVMIsAConstantArray),
  LLVM_SYMBOL(LLVMIsAConstantDataArray),
  LLVM_SYMBOL(LLVMIsAConstantFP),
  LLVM_SYMBOL(LLVMIsAConstantInt),
  LLVM_SYMBOL(LLVMIsAConstantStruct),
  LLVM_SYMBOL(LLVMIsAConstantVector),
  LLVM_SYMBOL(LLVMIsAFunction),
  LLVM_SYMBOL(LLVMIsAGlobalValue),
  LLVM_SYMBOL(LLVMIsAGlobalVariable),
  LLVM_SYMBOL(LLVMIsAPHINode),
  LLVM_SYMBOL(LLVMIsConstant),
  LLVM_SYMBOL(LLVMIsDeclaration),
  LLVM_SYMBOL(LLVMIsFunctionVarArg),
  LLVM_SYMBOL(LLVMIsGlobalConstant),
  LLVM_SYMBOL(LLVMIsLiteralStruct),
  LLVM_SYMBOL(LLVMIsNull),
  LLVM_SYMBOL(LLVMIsOpaqueStruct),
  LLVM_SYMBOL(LLVMIsPackedStruct),
  LLVM_SYMBOL(LLVMIsUndef),
  LLVM_SYMBOL(LLVMLinkInInterpreter),
  LLVM_SYMBOL(LLVMLinkInMCJIT),
  LLVM_SYMBOL(LLVMModuleCreateWithNameInContext),
  LLVM_SYMBOL(LLVMOffsetOfElement),
  LLVM_SYMBOL(LLVMPPCFP128TypeInContext),
  LLVM_SYMBOL(LLVMPassManagerBuilderCreate),
  LLVM_SYMBOL(LLVMPassManagerBuilderDispose),
  LLVM_SYMBOL(LLVMPassManagerBuilderPopulateFunctionPassManager),
  LLVM_SYMBOL(LLVMPassManagerBuilderPopulateModulePassManager),
  LLVM_SYMBOL(LLVMPassManagerBuilderSetOptLevel),
  LLVM_SYMBOL(LLVMPassManagerBuilderSetSizeLevel),
  LLVM_SYMBOL(LLVMPointerSize),
  LLVM_SYMBOL(LLVMPointerSizeForAS),
  LLVM_SYMBOL(LLVMPointerType),
  LLVM_SYMBOL(LLVMPositionBuilderAtEnd),
  LLVM_SYMBOL(LLVMPositionBuilderBefore),
  LLVM_SYMBOL(LLVMPreferredAlignmentOfType),
  LLVM_SYMBOL(LLVMPrintModuleToString),
  LLVM_SYMBOL(LLVMPrintTypeToString),
  LLVM_SYMBOL(LLVMPrintValueToString),
  LLVM_SYMBOL(LLVMRemoveModule),
  LLVM_SYMBOL(LLVMRunFunctionPassManager),
  LLVM_SYMBOL(LLVMRunPassManager),
  LLVM_SYMBOL(LLVMSetGlobalConstant),
  LLVM_SYMBOL(LLVMSetInitializer),
  LLVM_SYMBOL(LLVMSetLinkage),
  LLVM_SYMBOL(LLVMSetModuleDataLayout),
  LLVM_SYMBOL(LLVMSetTarget),
  LLVM_SYMBOL(LLVMSetValueName2),
  LLVM_SYMBOL(LLVMSetVisibility),
  LLVM_SYMBOL(LLVMSizeOf),
  LLVM_SYMBOL(LLVMSizeOfTypeInBits),
  LLVM_SYMBOL(LLVMStoreSizeOfType),
  LLVM_SYMBOL(LLVMStructCreateNamed),
  LLVM_SYMBOL(LLVMStructSetBody),
  LLVM_SYMBOL(LLVMStructTypeInContext),
  LLVM_SYMBOL(LLVMTargetHasAsmBackend),
  LLVM_SYMBOL(LLVMTargetHasJIT),
  LLVM_SYMBOL(LLVMTargetHasTargetMachine),
  LLVM_SYMBOL(LLVMTargetMachineEmitToFile),
  LLVM_SYMBOL(LLVMTypeIsSized),
  LLVM_SYMBOL(LLVMTypeOf),
  LLVM_SYMBOL(LLVMVectorType),
  LLVM_SYMBOL(LLVMVerifyModule),
  LLVM_SYMBOL(LLVMVoidTypeInContext),
  LLVM_SYMBOL(LLVMX86FP80TypeInContext),
  LLVM_SYMBOL(LLVM_InitializeNativeAsmParser),
  LLVM_SYMBOL(LLVM_InitializeNativeAsmPrinter),
  LLVM_SYMBOL(LLVM_InitializeNativeDisassembler),
  LLVM_SYMBOL(LLVM_InitializeNativeTarget),
};

llvm_symbol_array llvm_symbols() {
  llvm_symbol_array array;
  array.ptr = &symbols[0];
  array.len = sizeof(symbols) / sizeof(symbols[0]);
  return array;
}
